### ISSUE TITLE
Improve time display

### ISSUE THREAD

**Issue by zesk06** [zolenas/agile-time-keeper#5]
Adding more time info:
- total elapsed time
- sequence remaining time

see below

![concept](https://user-images.githubusercontent.com/2828390/35778206-7ea82a82-09bb-11e8-89bc-48635d70aaa8.jpg)

**Comment by sos-freed** [comment]
first part done on : 0c0f3bc
 next steps : 
1/ arrange updateRemainingTime function to set the sequence remaining time.
2/ display the "elapsed time"
3/ enjoy
